[DEFAULT]
raw_data_dir = ./data/audio/mp4
raw_user_info = user_info.csv
raw_file_info = speech_record.csv
wav_data_dir = ./data/audio/wav
pp_data_dir = ./data/audio/pp_wav
case_info_path = ./config/case_info+fold.csv
#tabular_data_path = ./data/csv/tabular_data_site_ac.csv
#tabular_data_path = ./data/csv/tabular_data_site_ab.csv
#tabular_data_path = ./data/csv/tabular_data_site_bc.csv
tabular_data_path = ./data/csv/datasetA.csv

SIL_THRES = 0.1
SIL_MIN_LEN = 500
SIL_WIN_SIZE = 50
num_folds = 5
train_folds.0 = 2,3,4,1
train_folds.1 = 0,3,4,2
train_folds.2 = 0,1,4,3
train_folds.3 = 0,1,2,4
train_folds.4 = 1,2,3,0
val_folds.0 = 1
val_folds.1 = 2
val_folds.2 = 3
val_folds.3 = 4
val_folds.4 = 0
test_folds.0 = 0
test_folds.1 = 1
test_folds.2 = 2
test_folds.3 = 3
test_folds.4 = 4
word_types = 0
transform_method = 2
normalize_method = 1
cqt_shape = 84,128 
spec_shape = 342,128
mfcc_shape = 20,128
cqt_range = -80,0
spec_range = -80,0
mfcc_range = -100,200
batch_size = 32
use_shuffle = true
use_transform = true
use_oversampling = true
prob_time_shift	= 0.99
time_shift_size	= 0.1
prob_time_mask = 0.99
time_mask_size = 0.1
prob_value_scaling = 0.99
scaling_range = 0.8,1.2
prob_additive_noise = 0.99
noise_std = 0.01
prob_frequency_mask = 0.99
frequency_mask_size = 0.1
prob_time_stretching = 0.99
stretching_range = 0.5,1.5
epochs = 2000
input_channel = 1
num_classes = 1
dropout_rate = 0.25
model_output_dir = ./model_result_v
max_patience = 300
select_top_column = 
fi_path = ./ml_result/use_all/feature_importance.csv
mo_path = ./data/model_output.csv
esm_dir = ./esm_result/v3


